name: ci

on:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config --local user.name "paulhouston560"
          git config --local user.email "216162100+paulhouston560@users.noreply.github.com" 
          git add .
          git commit -m "update"
          git push
