name: test
on:

  workflow_dispatch:

  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # 每天的 0:00 执行

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup random commit script
        run: |
          echo "cmFuZG9tX251bT0kKChSQU5ET00gJSA1ICsgMSkpCgplY2hvICLnlJ/miJDnmoTpmo/mnLrmlbDlrZfmmK86ICRyYW5kb21fbnVtIgoKIyDov5vooYzmnaHku7bliKTmlq0KaWYgWyAkcmFuZG9tX251bSAtZXEgMSBdOyB0aGVuCiAgICAjIOeUn+aIkCAxIOWIsCA1IOS5i+mXtOeahOmaj+acuuaVsAogICAgbj0kKCggUkFORE9NICUgNSArIDEgKSkKICAgIGVjaG8gIuW+queOr+asoeaVsO+8miRuIgoKICAgICMg5b6q546vIG4g5qyh77yM5q+P5qyh5bCGIGRhdGUg6L+95Yqg5YaZ5YWl5YiwIHRlc3QudHh077yM5bm26ZqP5py6562J5b6FIDEtNjAg56eSCiAgICBmb3IgKCggaT0xOyBpPD1uOyBpKysgKSk7IGRvCiAgICAgIGVjaG8gIuesrCAkaSDmrKHlhpnlhaXvvJoiCiAgICAgIGRhdGUgPj4gdGVzdC50eHQKICAgICAgIyDnlJ/miJAx5YiwNjDnmoTpmo/mnLrnp5LmlbAKICAgICAgd2FpdF90aW1lPSQoKFJBTkRPTSAlIDYwICsgMSkpCiAgICAgIHNsZWVwICR3YWl0X3RpbWUKICAgIGRvbmUKCiAgICBlY2hvICLov73liqDlhpnlhaXlhajpg6jlrozmiJDjgIIiCmVsaWYgWyAkcmFuZG9tX251bSAtZXEgMiBdOyB0aGVuCiAgICAjIOeUn+aIkCAxIOWIsCA1IOS5i+mXtOeahOmaj+acuuaVsAogICAgbj0kKCggUkFORE9NICUgNSArIDEgKSkKICAgIGVjaG8gIuW+queOr+asoeaVsO+8miRuIgoKICAgICMg5b6q546vIG4g5qyh77yM5q+P5qyh5bCGIGRhdGUg6KaG55uW5YaZ5YWl5YiwIHRlc3QudHh077yM5bm26ZqP5py6562J5b6FIDEtNjAg56eSCiAgICBmb3IgKCggaT0xOyBpPD1uOyBpKysgKSk7IGRvCiAgICAgIGVjaG8gIuesrCAkaSDmrKHlhpnlhaXvvJoiCiAgICAgICMg5aaC5p6c5L2g5oOz6KaB6L+95Yqg6ICM5LiN5piv6KaG55uW77yM6K+35pS55Li677yaZGF0ZSA+PiB0ZXN0LnR4dAogICAgICBkYXRlID4gdGVzdC50eHQKICAgICAgIyDnlJ/miJAx5YiwNjDnmoTpmo/mnLrnp5LmlbAKICAgICAgd2FpdF90aW1lPSQoKFJBTkRPTSAlIDYwICsgMSkpCiAgICAgIHNsZWVwICR3YWl0X3RpbWUKICAgIGRvbmUKCiAgICBlY2hvICLopobnm5blhpnlhaXlhajpg6jlrozmiJDjgIIiCmVsc2UKICAgIGVjaG8gIuaVsOWtl+aYryAkcmFuZG9tX251be+8jOS4jeaJp+ihjOS7u+S9leaTjeS9nCIKZmk=" | base64 -d | bash
          git config --local user.email "216162100+paulhouston560@users.noreply.github.com" 
          git config --local user.name "paulhouston560"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git add .
          git commit -m "update"
          git push
