name: test
on:

  workflow_dispatch:

  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # 每天的 0:00 执行

jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config --local user.email "216162100+paulhouston560@users.noreply.github.com" 
          git config --local user.name "paulhouston560"
       
      - name: Setup random commit script
        run: |
          echo "cmFuZG9tX251bT0kKChSQU5ET00gJSAzICsgMSkpCgplY2hvICLnlJ/miJDnmoTpmo/mnLrmlbDlrZfmmK86ICRyYW5kb21fbnVtIgoKIyDov5vooYzmnaHku7bliKTmlq0KaWYgWyAkcmFuZG9tX251bSAtZXEgMSBdOyB0aGVuCiAgICAjIOeUn+aIkCAxIOWIsCA1IOS5i+mXtOeahOmaj+acuuaVsAogICAgbj0kKCggUkFORE9NICUgNSArIDEgKSkKICAgIGVjaG8gIuW+queOr+asoeaVsO+8miRuIgoKICAgICMg5b6q546vIG4g5qyh77yM5q+P5qyh5bCGIGRhdGUg6L+95Yqg5YaZ5YWl5YiwIHRlc3QudHh077yM5bm26ZqP5py6562J5b6FIDEtNjAg56eSCiAgICBmb3IgKCggaT0xOyBpPD1uOyBpKysgKSk7IGRvCiAgICAgIGVjaG8gIuesrCAkaSDmrKHlhpnlhaXvvJoiCiAgICAgIGRhdGUgPj4gdGVzdC50eHQKICAgICAgZ2l0IGNvbW1pdCAtbSAidXBkYXRlIgogICAgICAjIOeUn+aIkDHliLA2MOeahOmaj+acuuenkuaVsAogICAgICB3YWl0X3RpbWU9JCgoUkFORE9NICUgNSArIDEpKQogICAgICBzbGVlcCAkd2FpdF90aW1lCiAgICBkb25lCgogICAgZWNobyAi6L+95Yqg5YaZ5YWl5YWo6YOo5a6M5oiQ44CCIgplbGlmIFsgJHJhbmRvbV9udW0gLWVxIDIgXTsgdGhlbgogICAgIyDnlJ/miJAgMSDliLAgNSDkuYvpl7TnmoTpmo/mnLrmlbAKICAgIG49JCgoIFJBTkRPTSAlIDUgKyAxICkpCiAgICBlY2hvICLlvqrnjq/mrKHmlbDvvJokbiIKCiAgICAjIOW+queOryBuIOasoe+8jOavj+asoeWwhiBkYXRlIOimhuebluWGmeWFpeWIsCB0ZXN0LnR4dO+8jOW5tumaj+acuuetieW+hSAxLTYwIOenkgogICAgZm9yICgoIGk9MTsgaTw9bjsgaSsrICkpOyBkbwogICAgICBlY2hvICLnrKwgJGkg5qyh5YaZ5YWl77yaIgogICAgICBkYXRlID4gdGVzdC50eHQKICAgICAgZ2l0IGNvbW1pdCAtbSAidXBkYXRlIgogICAgICAjIOeUn+aIkDHliLA2MOeahOmaj+acuuenkuaVsAogICAgICB3YWl0X3RpbWU9JCgoUkFORE9NICUgNSArIDEpKQogICAgICBzbGVlcCAkd2FpdF90aW1lCiAgICBkb25lCgogICAgZWNobyAi6KaG55uW5YaZ5YWl5YWo6YOo5a6M5oiQ44CCIgplbHNlCiAgICBlY2hvICLmlbDlrZfmmK8gJHJhbmRvbV9udW3vvIzkuI3miafooYzku7vkvZXmk43kvZwiCmZp" | base64 -d | bash
          git add .
          git commit -m "update"
          git push          
