name: test
on:

  workflow_dispatch:

  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # 每天的 0:00 执行

jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup random commit script
        run: |
          git config --local user.email "216162100+paulhouston560@users.noreply.github.com" 
          git config --local user.name "paulhouston560"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          echo "cmFuZG9tX251bT0kKChSQU5ET00gJSAzICsgMSkpCgplY2hvICLnlJ/miJDnmoTpmo/mnLrmlbDlrZfmmK86ICRyYW5kb21fbnVtIgoKIyDov5vooYzmnaHku7bliKTmlq0KaWYgWyAkcmFuZG9tX251bSAtZXEgMSBdOyB0aGVuCiAgICAjIOeUn+aIkCAxIOWIsCA1IOS5i+mXtOeahOmaj+acuuaVsAogICAgbj0kKCggUkFORE9NICUgNSArIDEgKSkKICAgIGVjaG8gIuW+queOr+asoeaVsO+8miRuIgoKICAgICMg5b6q546vIG4g5qyh77yM5q+P5qyh5bCGIGRhdGUg6L+95Yqg5YaZ5YWl5YiwIHRlc3QudHh077yM5bm26ZqP5py6562J5b6FIDEtNjAg56eSCiAgICBmb3IgKCggaT0xOyBpPD1uOyBpKysgKSk7IGRvCiAgICAgIGVjaG8gIuesrCAkaSDmrKHlhpnlhaXvvJoiCiAgICAgIGRhdGUgPj4gdGVzdC50eHQKICAgICAgZ2l0IGNvbW1pdCAtbSAidXBkYXRlIgogICAgICAjIOeUn+aIkDHliLA2MOeahOmaj+acuuenkuaVsAogICAgICB3YWl0X3RpbWU9JCgoUkFORE9NICUgNjAgKyAxKSkKICAgICAgc2xlZXAgJHdhaXRfdGltZQogICAgZG9uZQoKICAgIGVjaG8gIui/veWKoOWGmeWFpeWFqOmDqOWujOaIkOOAgiIKZWxpZiBbICRyYW5kb21fbnVtIC1lcSAyIF07IHRoZW4KICAgICMg55Sf5oiQIDEg5YiwIDUg5LmL6Ze055qE6ZqP5py65pWwCiAgICBuPSQoKCBSQU5ET00gJSA1ICsgMSApKQogICAgZWNobyAi5b6q546v5qyh5pWw77yaJG4iCgogICAgIyDlvqrnjq8gbiDmrKHvvIzmr4/mrKHlsIYgZGF0ZSDopobnm5blhpnlhaXliLAgdGVzdC50eHTvvIzlubbpmo/mnLrnrYnlvoUgMS02MCDnp5IKICAgIGZvciAoKCBpPTE7IGk8PW47IGkrKyApKTsgZG8KICAgICAgZWNobyAi56ysICRpIOasoeWGmeWFpe+8miIKICAgICAgIyDlpoLmnpzkvaDmg7PopoHov73liqDogIzkuI3mmK/opobnm5bvvIzor7fmlLnkuLrvvJpkYXRlID4+IHRlc3QudHh0CiAgICAgIGRhdGUgPiB0ZXN0LnR4dAogICAgICBnaXQgY29tbWl0IC1tICJ1cGRhdGUiCiAgICAgICMg55Sf5oiQMeWIsDYw55qE6ZqP5py656eS5pWwCiAgICAgIHdhaXRfdGltZT0kKChSQU5ET00gJSA2MCArIDEpKQogICAgICBzbGVlcCAkd2FpdF90aW1lCiAgICBkb25lCgogICAgZWNobyAi6KaG55uW5YaZ5YWl5YWo6YOo5a6M5oiQ44CCIgplbHNlCiAgICBlY2hvICLmlbDlrZfmmK8gJHJhbmRvbV9udW3vvIzkuI3miafooYzku7vkvZXmk43kvZwiCmZp" | base64 -d | bash
          git push
